name: build
on:
  workflow_dispatch:

jobs:
  build_windows_64bit:
    runs-on: ubuntu-24.04
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bash bc bison bzip2 ca-certificates ccache clang mingw-w64 ninja-build pkgconf python3 python3-pip python3-venv python3-yaml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build QEMU for Windows 64-bit
        run: |
          export CROSS_PREFIX=x86_64-w64-mingw32-
          export PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig
          mkdir build
          cd build
          ../configure --cross-prefix=$CROSS_PREFIX --target-list=x86_64-softmmu --enable-lzfse --disable-werror
          make -j$(nproc)
      - name: Install QEMU for Windows 64-bit
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install
      - name: Publish binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows_64bit
          path: ${{ github.workspace }}/bin/
